# **Sprint 3** - Tasca 4: Pràctica amb programació numèrica

## Exercici 1

In [17]:
import numpy as np
import pandas as pd

def resumEstadistic(dades):   
    #comprovem que es tracti d'un array d'una dimensió
    if dades.ndim == 1:
        # fem servir el mètode describe de Pandas per obtenir el resum estadístic
        return pd.DataFrame(dades).describe()
    else: return "S'espera un array d'una dimensió"
    
# fem la prova amb un array d una dimensió
resumEstadistic(np.random.randint(100, size=(50)))


0
count  50.00000
mean   58.02000
std    25.91705
min     6.00000
25%    33.50000
50%    63.50000
75%    80.75000
max    99.00000

## Exercici 2

In [21]:
import numpy as np

def creaQuadrat(n):
    return np.random.randint(100, size=(n,n))
    
creaQuadrat(4)

array([[ 3, 31, 75, 92],
       [92, 29, 10, 92],
       [89,  9, 13,  1],
       [56, 60,  7, 78]])

## Exercici 3

In [36]:
import numpy as np

def totals(taula):
    return np.sum([taula[0], taula[1]], axis=1), np.sum([taula[0], taula[1]], axis=0)
    
    
# fem la prova amb un array de dues dimensions random
taula1 = np.random.randint(100, size=(2,4))
resultat = totals(taula1)

print("La taula origina és: {}".format(taula1))
print("Els totals per fila son: {} i els totals per columna: {}".format(resultat[0], resultat[1]))

La taula origina és: [[26 71 97  1]
 [ 2  1 67 98]]
Els totals per fila son: [195 168] i els totals per columna: [ 28  72 164  99]


## Exercici 4

In [66]:
import numpy as np


def coeficientCorrelacio(x,y):
    
    xx= x-np.mean(x)
    yy= y-np.mean(y)
    xy= xx*yy
    
    xx2 = np.power(xx, 2)
    yy2 = np.power(yy, 2)
    
    return xy.sum()/(np.sqrt(xx2.sum())*np.sqrt(yy2.sum()))
    

# creem dos arrays per provar la funció

arr1 = np.arange(10, 20)
arr2 = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

# provem la funció creada

print(coeficientCorrelacio(arr1,arr2))

# comprovem el resultat amb la funció propia de Pandas

print(np.corrcoef(arr1,arr2))


0.758640289091187
[[1.         0.75864029]
 [0.75864029 1.        ]]
